toppase/toppase/apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import password_reset_confirm
from .views import LoginBusinessView, LogoutView, UpdateMemberBusinessView, PasswordResetBusinessView, UpdateMemberBusinessSettingsStoreCourierView, UpdateMemberBusinessSettingsStoreView, UpdateMemberBusinessSettingsStoreDesignView, UpdateMemberBusinessNotificationView


_password_reset = 'password/reset/'
_verify_pattern_token = "/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})"

urlpatterns = [
    # Login Client
    url(r'^user/login/',
        LoginBusinessView.as_view(),
        name='login'),
    # Logout Client
    url(r'^user/logout/',
        LogoutView.as_view(),
        name='logout'),
    # Update Profile Business
    url(r'^user/profile/$',
        UpdateMemberBusinessView.as_view(),
        name='profile'),
    # Update Member Notifiaction Settings
    url(r'^user/profile/notifications$',
        UpdateMemberBusinessNotificationView.as_view(),
        name='notification-settings'),

    url(r'^%s$' % _password_reset,
        PasswordResetBusinessView.as_view(),
        name='reset-password-client'),
    # Landing Page view
    # url(r'^Landing_page/$',
    #     CreateOrUpdateLandigPageView.as_view(),
    #     name='Landing-page'
    #     ),
    # url(r'^%s%s/$' %
    #     (_password_reset, _verify_pattern_token),
    #     password_reset_confirm,
    #     {'template_name': 'accounts/change_password_landing_page.html',
    #      'post_reset_redirect': 'accounts/login/'},
    #     name="password-verify-business"),


# Update Member Store Settings
    url(r'^user/store/(?P<store_id>[0-9]+)/settings/$',
        UpdateMemberBusinessSettingsStoreView.as_view(),
        name='store-settings'),
    url(r'^user/store/(?P<store_id>[0-9]+)/settings/design/$',
        UpdateMemberBusinessSettingsStoreDesignView.as_view(),
        name='store-settings-design'),
    url(r'^user/store/(?P<store_id>[0-9]+)/settings/courier$',
        UpdateMemberBusinessSettingsStoreCourierView.as_view(),
        name='store-settings-courier'),

]

toppase/toppase/apps/design/urls.py
from django.conf.urls import url, include

from rest_framework.routers import DefaultRouter

from . import views
from views import CreateOrUpadateConfEmailView, CreateOrUpdateConfTriggerView
from ..accounts.views import CreateOrUpdateConfLandigPageView

# from .views import UserLoginView, SendMailView, SendTestView, \
#         CreateOrUpdateTemplatesView, StatisticsView, ReceiveNotificationsView, \
#     ListeMailsView
#
urlpatterns = [
    url(r'^create-templates/email/$',
        CreateOrUpadateConfEmailView.as_view(),
        name='create_templates_email'
        ),
    url(r'^create-templates/landing-page/$',
        CreateOrUpdateConfLandigPageView.as_view(),
        name='create_templates_landing_page'
        ),
    url(r'^create-templates/trigger/$',
        CreateOrUpdateConfTriggerView.as_view(),
        name='create_templates_trigger'
        ),

]

# This router is used for API
router = DefaultRouter()
router.register(r'StatusDelivery', views.StatusDeliveryViewSet)
router.register(r'Store', views.StoreViewSet)
router.register(r'TemplateEmail', views.TemplateemailViewSet)
router.register(r'ContentEmail', views.ContentEmailViewSet)
urlpatterns += [url(r'^api/', include(router.urls)), ]

toppase/toppase/config/urls.py
"""toppase URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

# from toppase.utils.views import RobotsTextView

urlpatterns = [
    # Admin
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),

    # Account - Login Business
    url(r'^', include('apps.accounts.urls')),
    # Design
    url(r'^loyalty/', include('apps.design.urls')),

    # Tracking - Business
    url(r'^tracking/', include('apps.trackings.urls')),

    #Oauth2 prvider

    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),

    # Robots
    # url(r'^robots.txt$', RobotsTextView.as_view()),
]

urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]

if not settings.DJANGO_STATICFILES:
    # Static and Media files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        # DEBUG TOOLBAR
        url(r'__debug__/', include(debug_toolbar.urls)),
    ]

toppase/toppase/apps/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from oauth2_provider.models import AbstractApplication

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
# from ..design.models import Design
from ..cores.lib import get_hostname
from .constants import LANG_TYPE, PROVIDER_CHOICE, SIZE, ALLIGNMENT, FONT, STORE_CAT,STATUS
from .managers import UserManager
from django.db import models
from ..abstract.models import LandingPage



class ConfigEmail(models.Model):
    """this class represents the TemplateConfigured Object"""
    font = models.CharField(max_length=20, choices=FONT, verbose_name=_('Font'), default='AR')
    color_menu = models.CharField(max_length=7, verbose_name=_('Color menu'), default='#ffffff')
    color_call_to_action = models.CharField(max_length=7, verbose_name=_('Color call to action'), default='#ffffff')
    allignment = models.CharField(max_length=20, choices=ALLIGNMENT, verbose_name=_('Alignment'), default='center')
    size = models.CharField(max_length=3, verbose_name=_('Size'),choices=SIZE)

    def __unicode__(self):
        return
    class Meta:
        abstract = True




class StatusDelivery(models.Model):
    name = models.CharField(max_length=15,
                            choices=STATUS,
                            unique=True
                             )
    code = models.CharField(max_length=15,
                            unique=True,
                            primary_key=True
                            )

    def __unicode__(self):
        return self.get_name_display()


class NotificationMixin(models.Model):
    news_letter = models.BooleanField(
        verbose_name=_('News Letter'),
        default=True,
        help_text=_('Get updates on new features activated to your account.')
    )
    via_email = models.BooleanField(
        verbose_name=_('E-mail Notification'),
        help_text=_('Receive notifications when status order change, '
                    'check bellow'),
        default= True
    )
    status_deliveries = models.ManyToManyField(StatusDelivery)
    platform = models.BooleanField(
        verbose_name=_('System notification'),
        default=True,
        help_text=_('Get notification when changes happen in your account')
    )

    class Meta:
        abstract = True


class AccessCMSMixin(models.Model):
    provider = models.CharField(
        verbose_name=_('Provider'),
        max_length=20,
        choices=PROVIDER_CHOICE,
    )
    # request_key = models.CharField(
    #     verbose_name=_('Request key'),
    #     max_length=200,
    #     null=True,
    #     blank=True
    # )
    #
    # request_secret = models.CharField(
    #     verbose_name=_('Request secret'),
    #     max_length=200,
    #     null=True,
    #     blank=True
    # )

    # token = models.CharField(
    #     verbose_name=_('TOKEN'),
    #     max_length=200,
    #     null=True,
    #     blank=True
    # )
    #
    # access_token_secret = models.CharField(
    #     verbose_name=_("Secret token"),
    #     max_length=200,
    #     null=True,
    #     blank=True
    # )

    class Meta:
        abstract = True


class AddressLineMixin(models.Model):
    address_line = models.CharField(
        verbose_name=_('Street Address'),
        max_length=200,
        blank=True,
        null=True
    )
    zip_code = models.CharField(
        verbose_name=_('Zip code'),
        max_length=60,
        blank=True,
        null=True
    )
    city = models.CharField(
        verbose_name=_('City'),
        max_length=60,
        blank=True,
        null=True
    )
    country = models.CharField(
        verbose_name=_('Country'),
        max_length=100,
        default=_('France'),
        blank=True,
        null=True
    )

    class Meta:
        abstract = True

    def complete_address(self):
        return '{}, {} {} {}'.format(self.address_line, self.city,
                                     self.zip_code, self.country)


class PersonMixin(models.Model):
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=30)

    phone = models.CharField(
        verbose_name=_("Phone number"),
        max_length=20,
        help_text=_("Enter your phone"),
        null=True,
        blank=True,
        unique=True
    )

    class Meta:
        abstract = True

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name


class Member(AbstractBaseUser, PersonMixin, PermissionsMixin,
             NotificationMixin, AbstractApplication,):
    email = models.EmailField(
        verbose_name=_('Email address'),
        max_length=255,
        unique=True,
    )
    username = models.CharField(
        max_length=255,
        unique=True,
        null=True,
        blank=True,
    )

    language = models.CharField(
        verbose_name=_('Language'),
        max_length=50,
        choices=LANG_TYPE,
        default=LANG_TYPE[0][0],
        help_text=_('Choose your preferred language'),
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    objects = UserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    def get_short_name(self):
        return self.email

    def get_store(self):
        try:
            print "-------------"
            store = self.store_set.all()[0]
            print "-------------"
            print self.store_set.all()
            print store
            return store
        except IndexError as e:
            Exception(_("%s" % e))

    def get_content_emails(self):
        try:
            print "************++++++++++++++++++++++++++"
            store = self.get_store()
            print store
            print "************"
            content_email = store.contentemail_set.all()
            return content_email
        except IndexError as e:
            Exception(_("%s" % e))

    @property
    def is_business_member(self):
        """ Is the user of type business member """
        return not self.is_staff

    def get_store(self):
        try:
            return self.stores.all()[0]
        except IndexError as e:
            Exception(_("%s" % e))


class Courier(models.Model):
    text = models.CharField(
        verbose_name=_('Text Courier'),
        max_length=200
    )
    code = models.CharField(
        verbose_name=_('Code Courier'),
        max_length=200,
        unique=True,
        primary_key=True
    )

    def __unicode__(self):
        return "%s-%s" % (self.code, self.text)


class ConfigEmail(models.Model):
    """this class represents the TemplateConfigured Object"""
    font = models.CharField(max_length=20, choices=FONT, verbose_name=_('Font'), default='AR')
    color_menu = models.CharField(max_length=7, verbose_name=_('Color menu'), default='#ffffff')
    color_call_to_action = models.CharField(max_length=7, verbose_name=_('Color call to action'), default='#ffffff')
    allignment = models.CharField(max_length=20, choices=ALLIGNMENT, verbose_name=_('Alignment'), default='center')
    size = models.CharField(max_length=3, verbose_name=_('Size'), choices=SIZE)

    def __unicode__(self):
        return "configured Email"

    class Meta:
        abstract = True


class Advert(models.Model):
    link = models.URLField(verbose_name=_('Link'))
    image = models.ImageField(verbose_name=_('Image'))


class ConfigTracking(models.Model):
    l_font = models.CharField(max_length=20, choices=FONT, verbose_name=_('Landing page Font'), default='AR')
    l_color_menu = models.CharField(max_length=7, verbose_name=_('Landing page  Color menu'), default='#00ff00')
    l_color_call_to_action = models.CharField(max_length=7, verbose_name=_('Landing page  Color call to action'),
                                              default='#ff0000')
    l_allignment = models.CharField(max_length=20, choices=ALLIGNMENT, verbose_name=_('Landing page Alignment'),
                                    default='center')
    l_size = models.CharField(max_length=3, verbose_name=_('Landing page  Size'), choices=SIZE,default='12')
    l_background_image = models.ImageField(
        verbose_name=_('Landing page  Background image')
    )
    l_help_url = models.URLField(verbose_name=_('Landing page  HELP URL'))
    advert = models.ForeignKey(Advert, verbose_name=_("Landing page  Advert"), on_delete=models.CASCADE,null=True,blank=True)
    landing_page = models.ForeignKey(LandingPage, verbose_name=_("Landing page"), on_delete=models.CASCADE)

    def __unicode__(self):
        return "configue Tracking"

    class Meta:
        abstract = True


class Design(ConfigEmail, ConfigTracking):
    color_text = models.CharField(max_length=7,
                                  verbose_name=_('Color menu'),
                                  default='#ffffff')
    class Meta :
        abstract = True
    def __unicode__(self):
        return "design class"


class Store(Design, AccessCMSMixin, AddressLineMixin):
    company_name = models.CharField(
        verbose_name=_('Company Name'),
        max_length=200
    )
    name = models.CharField(
        verbose_name=_('Store Name'),

toppase/toppase/apps/design/forms.py
from django import forms
from django.forms import ModelForm
from ..accounts.models import Store
from models import ContentEmail



class ContentEmailForm(ModelForm):
    """This class represents the Content Email form"""


    class Meta:
        model = ContentEmail
        fields = ['template_email', 'text_body', 'text_footer']
        widgets = {
            'template_email' : forms.Select(attrs={'class':'form-control'}),
            'text_body': forms.Textarea(attrs={'class':'form-control','rows':'3','cols':'5'}),
            'text_footer': forms.Textarea(attrs={'class':'form-control','rows':'3','cols':'5'}),
        }


class ContentEmailForm(ModelForm):
    """This class represents the Content Email form"""

    class Meta:
        model = ContentEmail
        fields = ['template_email', 'text_body', 'text_footer']
        widgets = {

            'template_email': forms.Select(attrs={'class': 'form-control'}),
            'text_body': forms.Textarea(attrs={'class': 'form-control', 'rows': '3', 'cols': '5'}),
            'text_footer': forms.Textarea(attrs={'class': 'form-control', 'rows': '3', 'cols': '5'}),
        }
class ConfigEmailForm(ModelForm):
    """This class represents the Content Email form"""

    class Meta:
        model = Store
        fields = ['font', 'color_menu', 'color_call_to_action', 'allignment', 'size', ]
        widgets = {
            'allignment': forms.Select(attrs={'class': 'form-control'}),
            'size': forms.Select(attrs={'class': 'form-control'}),
            'font': forms.Select(attrs={'class': 'form-control', 'id': 'list_fonts'}),
            'color_call_to_action': forms.TextInput(attrs={'class': 'form-control'}),
            'color_menu': forms.TextInput(attrs={'class': 'form-control'}),
        }

toppase/toppase/templates/accounts/change_password_landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

toppase/toppase/templates/accounts/design.html
{% extends "business_plateforme.html" %}
{% load staticfiles %}

{% block title %}
    Store
{% endblock %}


{% block content %}
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card mx-10">
                    <div class="card-block p-4">


                        <form action="" method="post" id="StoreDesignFormID" name="StoreDesignFormName">
                            {% csrf_token %}
                            <fieldset>
                                <legend>Design</legend>
                                <p>You probably do not need to modify these settings. If you'd like to change the
                                   default font in your template, choose the font that is closest to your website.</p>
                                <div class="form-group">


                                    <div class="form-group row">
                                        <label class="col-3 col-form-label">Logo</label>
                                        <div class="col-4">
                                            <label class="custom-file"> <input type="file" id="file_logo"
                                                                               class="custom-file-input" name="logo">
                                                <span id="logo_name"
                                                      class="custom-file-control"></span> </label>
                                        </div>
                                        <label class="col-2 col-form-label">Logo:</label>
                                        <div style="width:150px;">
                                            <img id="logo" style="width:100%;"
                                                 src="" alt="logo">
                                        </div>
                                    </div>
                                    <strong>Menu Font & Color</strong>
                                    <div class="form-group row">
                                        <label for="example-text-input"
                                               class="col-3 col-form-label">Font Family</label>
                                        <div class="col-6">
                                            <select class="form-control" name="font" id="font">
                                                <option  value="AR">Arial</option>
                                                <option value="ARB">Arial Black</option>
                                                <option value="CN">Courier New</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group row">

                                        <label class="col-3 col-form-label">Color Menu</label>
                                        <div class="col-6">
                                            <div id="cp2" class="input-group colorpicker-component">
                                                <input type="text" value="#00AABB" class="form-control" id="color_menu"
                                                       name="color_menu"/> <span
                                                    class="input-group-addon"><i></i></span>
                                            </div>
                                            <script>
                                                $(function () {
                                                    $('#cp2').colorpicker();
                                                });
                                            </script>
                                        </div>
                                    </div>
                                    <div class="form-group row">

                                        <label class="col-3 col-form-label">Color Text</label>
                                        <div class="col-6">
                                            <div id="cp3" class="input-group colorpicker-component">
                                                <input type="text" value="#00AA00" class="form-control"
                                                       name="color_text" id="color_text"/> <span
                                                    class="input-group-addon"><i></i></span>
                                            </div>
                                            <script>
                                                $(function () {
                                                    $('#cp3').colorpicker();
                                                });
                                            </script>
                                        </div>
                                    </div>


                                    <strong>Web Links</strong>
                                    <div class="web"></div>

                                    </div>

                                    <button id="add_web_links" type="button"
                                            class="btn btn-link px-0">add web links
                                    </button>

                                    <br> <strong>Social Links</strong>
                                    <span> to add later (need to add a social link model)</span>

{#                                    <div class="social"></div>#}
{#                                    <div class="form-group row social">#}
{##}
{#                                        <div class="col-2">#}
{#                                            <select class="form-control">#}
{#                                                <option selected>Twitter</option>#}
{#                                                <option value="1">Facebook</option>#}
{#                                                <option value="2">LinkenIn</option>#}
{#                                            </select>#}
{#                                        </div>#}
{##}
{##}
{#                                        <label class="col-1 col-form-label">Text</label>#}
{#                                        <div class="col-2">#}
{#                                            <input class="form-control" type="text">#}
{#                                        </div>#}
{##}
{##}
{#                                        <label class="col-1 col-form-label">URL</label>#}
{#                                        <div class="col-4">#}
{#                                            <input class="form-control" type="url">#}
{#                                        </div>#}
{##}
{#                                        <div class="col-1">#}
{#                                            <button type="button" class="close"#}
{#                                                    aria-label="Close">#}
{#                                                <span aria-hidden="true">&times;</span>#}
{#                                            </button>#}
{#                                        </div>#}
{##}
{#                                    </div>#}
{##}
{##}
{#                                    <button id="add_social_links" type="button"#}
{#                                            class="btn btn-link px-0">add social links#}
{#                                    </button>#}


{#                                </div>#}
                            </fieldset>

                            <center>
                                <button type="submit" class="btn btn-success">Save Changes
                                </button>
                            </center>

                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}

toppase/toppase/templates/accounts/my_profile_notifications.html
{% extends "accounts/profile.html" %}
{% load staticfiles %}

{% block title %}
    My Profile
{% endblock %}

{% block template_to_include %}
    {% include "accounts/notifications.html" %}
{% endblock %}
{% block profile-class %}
    class="nav-link"
{% endblock %}
{% block profile-url %}
    href='{% url "profile" %}'
{% endblock %}
{% block notification-settings-class%}
    class="nav-link active"
{% endblock %}
{% block notification-settings-url %}
    href="#"
{% endblock %}

toppase/toppase/templates/accounts/my_profile_user.html
{% extends "accounts/profile.html" %}
{% load staticfiles %}

{% block title %}
    My Profile
{% endblock %}

{% block template_to_include %}
    {% include "accounts/user.html" %}
{% endblock %}
{% block profile-class %}
     class="nav-link active"
{% endblock %}
{% block profile-url %}
    href="#"
{% endblock %}
{% block notification-settings-class%}
     class="nav-link"
{% endblock %}
{% block notification-settings-url %}
    href='{% url "notification-settings" %}'
{% endblock %}

toppase/toppase/templates/accounts/notifications.html
{% extends "business_plateforme.html" %}
{% load staticfiles %}

{% block title %}
    My Profile
{% endblock %}
{% block style %}


{% endblock %}

{% block body_classes %}

{% endblock %}

{% block content %}

    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card mx-10">
                    <div class="card-block p-4">




                        <form method="post" action="">
                            {% csrf_token %}
                            <fieldset>
                                <legend>Notifications Prefrences</legend>
                                <p style="margin-bottom:30px;">Check the
                                                               notifications you would like to receive</p>


                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input class="form-check-input"
                                               type="checkbox" value="system"> <B>System
                                                                                  Notifications</B>
                                    </label>
                                </div>
                                <p style="color: #9a9898; margin-left: 25px">Get notifications when changes occur to your
                                                                             Account</p>

                                <div class="form-check">
                                    <label class="form-check-label">
                                        {{ form_notifications.via_email }}<B>Email
                                                                             Notifications</B>
                                    </label>
                                    {% if form_notifications.via_email.errors %}
                                        {% for error in form_notifications.via_email.errors %}
                                            <div class="alert alert-danger" role="alert">
                                                <strong>{{ error }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endif %}

                                </div>
                                <p style="color: #9a9898; margin-left: 25px">Receive Notifications when the status order
                                                                             changes:</p>

                                <div class="center-block" style="margin-left: 25px; color: #9a9898;">
                                    <div class="form-check form-check-inline">
                                        <label class="form-check-label">
                                            {#                                            {{ form_notifications.status_deliveries }}#}
                                            <select name="status_deliveries"  multiple="multiple" class="form-check-input" id="id_status_deliveries">
                                                <option value="1" selected="">in transit</option>

                                            </select>
                                        </label>
                                        {% if form_notifications.status_deliveries.errors %}
                                            {% for error in form_notifications.status_deliveries.errors %}
                                                <div class="alert alert-danger" role="alert">
                                                    <strong>{{ error }}</strong>
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>

                                </div>

                                <div class="form-check">
                                    <label class="form-check-label">
                                        {{ form_notifications.news_letter }}<B>NewsLetter</B>
                                    </label>
                                    {% if form_notifications.news_letter.errors %}
                                        {% for error in form_notifications.news_letter.errors %}
                                            <div class="alert alert-danger" role="alert">
                                                <strong>{{ error }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <p style="color: #9a9898; margin-left: 25px">Get updates on feautures activated on your
                                                                             account </p>


                            </fieldset>
                            <center>
                                <button type="submit" class="btn btn-success">Save Changes</button>
                            </center>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>







{% endblock %}

toppase/toppase/templates/accounts/store_settings_courier.html
{% extends "accounts/store_settings.html" %}
{% load staticfiles %}
{% block template_to_include %}
    {% include "accounts/courier.html" %}
{% endblock %}
{% block store-class %}
    class="nav-link"
{% endblock %}
{% block store-url %}
    href='{% url "store-settings" request.user.get_store.pk %}'
{% endblock %}
{% block design-class %}
    class="nav-link"
{% endblock %}
{% block design-url %}
    href='{% url "store-settings-design" request.user.get_store.pk %}'
{% endblock %}
{% block courier-class %}
    class="nav-link active"
{% endblock %}
{% block courier-url %}
    href="#"
{% endblock %}